dataset_nums = [1, 2, 3, 5, 6, 7]
sequence_sizes = [5, 10, 15]
future_predicts = [1, 3, 5]
# dataset_nums = [1]
# sequence_sizes = [5, 10, 15]
# future_predicts = [1, 3, 5]
learning_rate = 0.001
batch_size = 16
hidden_layers_separate_models = 0
hidden_layers_hyper_models = 3
number_of_rounds = 10
test_data_filename = 'test_dataset.csv'
