dataset_nums = [1, 2, 3, 5, 6, 7]
# dataset_nums = [1, 2]
learning_rate = 0.001
sequence_size = 15
batch_size = 16
hidden_layers_separate_models = 0
hidden_layers_hyper_models = 3
number_of_rounds = 10
test_data_filename = 'test_dataset.csv'
